name: "Build APK 🚀"

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.3

      - name: Set up JDK environment
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 11

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Lint
        run: ./gradlew lint

      - name: Clean
        run: ./gradlew clean

      - name: Run Unit Tests
        run: ./gradlew test

      - name: Decode Keystore
        id: decode_keystore
        uses: timheuer/base64-to-file@v1
        with:
          fileName: 'keystore/keystore.jks'
          encodedString: ${{ secrets.KEYSTORE }}

      - name: Build Artifacts
        id: buildAllAabs
        uses: eskatos/gradle-command-action@v1.3.3
        env:
          SIGNING_BASE64: ${{steps.decode_keystore.outputs.filePath}}
          SIGNING_KEY_ALIAS: ${{ secrets.KEYALIAS }}
          SIGNING_KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          SIGNING_STORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          CI: true
        with:
          gradle-version: 7.2
          wrapper-cache-enabled: true
          dependencies-cache-enabled: true
          configuration-cache-enabled: true
          arguments: assembleRelease

        # Run on android emulator
        # uses: reactivecircus/android-emulator-runner@v2
        #   with:
        #     api-level: 23
        #     target: default
        #     arch: x86
        #     profile: Nexus 6
        #     script: ./gradlew connectedCheck --stacktrace

      - name: Upload APK
        uses: actions/upload-artifact@v2.2.0
        with:
          name: Release artifact
          path: D:\Android\TP_note\app\build\outputs\apk\debug\

      - name: Discord notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          DISCORD_USERNAME: Github Action
        uses: Ilshidur/action-discord@master
        with:
          args: 'La nouvelle version est disponible !'

      - name: Send file apk to discord channel
        uses: sinshutu/upload-to-discord@master
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        with:
          args: app/build/outputs/apk/release/app-monpotager-*.apk
